name: Test document and figures in root folder

on:
  # push on master branch
  push:
    branches: [master]
  # triggered manually
  workflow_dispatch:
  # triggered by pull requests
  pull_request:

jobs:
  defaults:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cagix/pandoc-thesis@master
      - uses: actions/upload-artifact@v4
        with:
          name: thesis_defaults
          path: thesis.pdf
          overwrite: true
  eisvogel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cagix/pandoc-thesis@master
        with:
          srcfile: thesis.md
          targetfile: thesis-eisvogel.pdf
          bibfile: references.bib
          template: eisvogel
      - uses: actions/upload-artifact@v4
        with:
          name: thesis_eisvogel
          path: thesis-eisvogel.pdf
          overwrite: true
  simple:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cagix/pandoc-thesis@master
        with:
          srcfile: thesis.md
          targetfile: thesis-simple.pdf
          bibfile: references.bib
          template: simple
      - uses: actions/upload-artifact@v4
        with:
          name: thesis_simple
          path: thesis-simple.pdf
          overwrite: true
